"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const React = __importStar(require("react"));
const BS = __importStar(require("react-bootstrap"));
const common_1 = require("../common");
const vortex_api_1 = require("vortex-api");
const react_i18next_1 = require("react-i18next");
function InfoComponent(props) {
    const { onToggleModsState } = props;
    const t = (0, react_i18next_1.useTranslation)(common_1.I18N_NAMESPACE).t;
    const toggleModsState = React.useCallback((enable) => {
        onToggleModsState(enable);
    }, [onToggleModsState]);
    return (React.createElement(BS.Panel, { id: 'loadorderinfo' },
        React.createElement("h2", null, t('Managing your load order', { ns: common_1.I18N_NAMESPACE })),
        React.createElement(vortex_api_1.FlexLayout.Flex, { style: { height: '30%' } },
            React.createElement("div", null,
                React.createElement("p", null,
                    t('You can adjust the load order for The Witcher 3 by dragging and dropping '
                        + 'mods up or down on this page.  If you are using several mods that add scripts you may need to use '
                        + 'the Witcher 3 Script merger. For more information see: ', { ns: common_1.I18N_NAMESPACE }),
                    React.createElement("a", { onClick: () => vortex_api_1.util.opn('https://wiki.nexusmods.com/index.php/Modding_The_Witcher_3_with_Vortex') }, t('Modding The Witcher 3 with Vortex.', { ns: common_1.I18N_NAMESPACE })))),
            React.createElement("div", { style: { height: '80%' } },
                React.createElement("p", null, t('Please note:', { ns: common_1.I18N_NAMESPACE })),
                React.createElement("ul", null,
                    React.createElement("li", null, t('For Witcher 3, the mod with the lowest index number (by default, the mod sorted at the top) overrides mods with a higher index number.', { ns: common_1.I18N_NAMESPACE })),
                    React.createElement("li", null, t('You are able to modify the priority manually by right clicking any LO entry and set the mod\'s priority', { ns: common_1.I18N_NAMESPACE })),
                    React.createElement("li", null, t('If you cannot see your mod in this load order, you may need to add it manually (see our wiki for details).', { ns: common_1.I18N_NAMESPACE })),
                    React.createElement("li", null, t('When managing menu mods, mod settings changed inside the game will be detected by Vortex as external changes - that is expected, '
                        + 'choose to use the newer file and your settings will be made persistent.', { ns: common_1.I18N_NAMESPACE })),
                    React.createElement("li", null, t('You can change the way the priorities are assgined using the "Switch To Position/Prefix based" button. '
                        + 'Prefix based is less restrictive and allows you to set any priority value you want "5000, 69999, etc" while position based will '
                        + 'restrict the priorities to the number of load order entries that are available.', { ns: common_1.I18N_NAMESPACE })),
                    React.createElement("li", null, t('Merges generated by the Witcher 3 Script merger must be loaded first and are locked in the first load order slot.', { ns: common_1.I18N_NAMESPACE }))),
                React.createElement(BS.Button, { onClick: () => toggleModsState(false), style: { marginBottom: '5px', width: 'min-content' } }, t('Disable All')),
                React.createElement("br", null),
                React.createElement(BS.Button, { onClick: () => toggleModsState(true), style: { marginBottom: '5px', width: 'min-content' } }, t('Enable All '))))));
}
exports.default = InfoComponent;
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiSW5mb0NvbXBvbmVudC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIkluZm9Db21wb25lbnQudHN4Il0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFDQSw2Q0FBK0I7QUFDL0Isb0RBQXNDO0FBQ3RDLHNDQUEyQztBQUUzQywyQ0FBOEM7QUFDOUMsaURBQStDO0FBTS9DLFNBQXdCLGFBQWEsQ0FBQyxLQUF5QjtJQUM3RCxNQUFNLEVBQUUsaUJBQWlCLEVBQUUsR0FBRyxLQUFLLENBQUM7SUFDcEMsTUFBTSxDQUFDLEdBQUcsSUFBQSw4QkFBYyxFQUFDLHVCQUFjLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFDM0MsTUFBTSxlQUFlLEdBQUcsS0FBSyxDQUFDLFdBQVcsQ0FBQyxDQUFDLE1BQU0sRUFBRSxFQUFFO1FBQ25ELGlCQUFpQixDQUFDLE1BQU0sQ0FBQyxDQUFDO0lBQzVCLENBQUMsRUFBRSxDQUFDLGlCQUFpQixDQUFDLENBQUMsQ0FBQztJQUV4QixPQUFPLENBQ0wsb0JBQUMsRUFBRSxDQUFDLEtBQUssSUFBQyxFQUFFLEVBQUMsZUFBZTtRQUMxQixnQ0FBSyxDQUFDLENBQUMsMEJBQTBCLEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDLENBQU07UUFDaEUsb0JBQUMsdUJBQVUsQ0FBQyxJQUFJLElBQUMsS0FBSyxFQUFFLEVBQUUsTUFBTSxFQUFFLEtBQUssRUFBRTtZQUN2QztnQkFDRTtvQkFDRyxDQUFDLENBQUMsMkVBQTJFOzBCQUMxRSxvR0FBb0c7MEJBQ3BHLHlEQUF5RCxFQUFFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQztvQkFDdEYsMkJBQUcsT0FBTyxFQUFFLEdBQUcsRUFBRSxDQUFDLGlCQUFJLENBQUMsR0FBRyxDQUFDLHdFQUF3RSxDQUFDLElBQ2pHLENBQUMsQ0FBQyxvQ0FBb0MsRUFBRSxFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUMsQ0FDOUQsQ0FDRixDQUNBO1lBQ04sNkJBQUssS0FBSyxFQUFFLEVBQUUsTUFBTSxFQUFFLEtBQUssRUFBRTtnQkFDM0IsK0JBQUksQ0FBQyxDQUFDLGNBQWMsRUFBRSxFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUMsQ0FBSztnQkFDbEQ7b0JBQ0UsZ0NBQUssQ0FBQyxDQUFDLHdJQUF3SSxFQUFFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQyxDQUFNO29CQUM5SyxnQ0FBSyxDQUFDLENBQUMseUdBQXlHLEVBQUUsRUFBRSxFQUFFLEVBQUUsdUJBQWMsRUFBRSxDQUFDLENBQU07b0JBQy9JLGdDQUFLLENBQUMsQ0FBQyw0R0FBNEcsRUFBRSxFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUMsQ0FBTTtvQkFDbEosZ0NBQUssQ0FBQyxDQUFDLG1JQUFtSTswQkFDdEkseUVBQXlFLEVBQzNFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQyxDQUFNO29CQUMvQixnQ0FBSyxDQUFDLENBQUMseUdBQXlHOzBCQUM1RyxrSUFBa0k7MEJBQ2xJLGlGQUFpRixFQUNuRixFQUFFLEVBQUUsRUFBRSx1QkFBYyxFQUFFLENBQUMsQ0FBTTtvQkFDL0IsZ0NBQUssQ0FBQyxDQUFDLG1IQUFtSCxFQUFFLEVBQUUsRUFBRSxFQUFFLHVCQUFjLEVBQUUsQ0FBQyxDQUFNLENBQ3RKO2dCQUNMLG9CQUFDLEVBQUUsQ0FBQyxNQUFNLElBQ1IsT0FBTyxFQUFFLEdBQUcsRUFBRSxDQUFDLGVBQWUsQ0FBQyxLQUFLLENBQUMsRUFDckMsS0FBSyxFQUFFLEVBQUUsWUFBWSxFQUFFLEtBQUssRUFBRSxLQUFLLEVBQUUsYUFBYSxFQUFFLElBRW5ELENBQUMsQ0FBQyxhQUFhLENBQUMsQ0FDUDtnQkFDWiwrQkFBTTtnQkFDTixvQkFBQyxFQUFFLENBQUMsTUFBTSxJQUNSLE9BQU8sRUFBRSxHQUFHLEVBQUUsQ0FBQyxlQUFlLENBQUMsSUFBSSxDQUFDLEVBQ3BDLEtBQUssRUFBRSxFQUFFLFlBQVksRUFBRSxLQUFLLEVBQUUsS0FBSyxFQUFFLGFBQWEsRUFBRSxJQUVuRCxDQUFDLENBQUMsYUFBYSxDQUFDLENBQ1AsQ0FDUixDQUNVLENBQ1QsQ0FDWixDQUFDO0FBQ0osQ0FBQztBQXJERCxnQ0FxREMiLCJzb3VyY2VzQ29udGVudCI6WyIvKiBlc2xpbnQtZGlzYWJsZSAqL1xyXG5pbXBvcnQgKiBhcyBSZWFjdCBmcm9tICdyZWFjdCc7XHJcbmltcG9ydCAqIGFzIEJTIGZyb20gJ3JlYWN0LWJvb3RzdHJhcCc7XHJcbmltcG9ydCB7IEkxOE5fTkFNRVNQQUNFIH0gZnJvbSAnLi4vY29tbW9uJztcclxuXHJcbmltcG9ydCB7IEZsZXhMYXlvdXQsIHV0aWwgfSBmcm9tICd2b3J0ZXgtYXBpJztcclxuaW1wb3J0IHsgdXNlVHJhbnNsYXRpb24gfSBmcm9tICdyZWFjdC1pMThuZXh0JztcclxuXHJcbmludGVyZmFjZSBJbmZvQ29tcG9uZW50UHJvcHMge1xyXG4gIG9uVG9nZ2xlTW9kc1N0YXRlOiAoZW5hYmxlOiBib29sZWFuKSA9PiB2b2lkO1xyXG59XHJcblxyXG5leHBvcnQgZGVmYXVsdCBmdW5jdGlvbiBJbmZvQ29tcG9uZW50KHByb3BzOiBJbmZvQ29tcG9uZW50UHJvcHMpIHtcclxuICBjb25zdCB7IG9uVG9nZ2xlTW9kc1N0YXRlIH0gPSBwcm9wcztcclxuICBjb25zdCB0ID0gdXNlVHJhbnNsYXRpb24oSTE4Tl9OQU1FU1BBQ0UpLnQ7XHJcbiAgY29uc3QgdG9nZ2xlTW9kc1N0YXRlID0gUmVhY3QudXNlQ2FsbGJhY2soKGVuYWJsZSkgPT4ge1xyXG4gICAgb25Ub2dnbGVNb2RzU3RhdGUoZW5hYmxlKTtcclxuICB9LCBbb25Ub2dnbGVNb2RzU3RhdGVdKTtcclxuXHJcbiAgcmV0dXJuIChcclxuICAgIDxCUy5QYW5lbCBpZD0nbG9hZG9yZGVyaW5mbyc+XHJcbiAgICAgIDxoMj57dCgnTWFuYWdpbmcgeW91ciBsb2FkIG9yZGVyJywgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9PC9oMj5cclxuICAgICAgPEZsZXhMYXlvdXQuRmxleCBzdHlsZT17eyBoZWlnaHQ6ICczMCUnIH19PlxyXG4gICAgICAgIDxkaXY+XHJcbiAgICAgICAgICA8cD5cclxuICAgICAgICAgICAge3QoJ1lvdSBjYW4gYWRqdXN0IHRoZSBsb2FkIG9yZGVyIGZvciBUaGUgV2l0Y2hlciAzIGJ5IGRyYWdnaW5nIGFuZCBkcm9wcGluZyAnXHJcbiAgICAgICAgICAgICAgKyAnbW9kcyB1cCBvciBkb3duIG9uIHRoaXMgcGFnZS4gIElmIHlvdSBhcmUgdXNpbmcgc2V2ZXJhbCBtb2RzIHRoYXQgYWRkIHNjcmlwdHMgeW91IG1heSBuZWVkIHRvIHVzZSAnXHJcbiAgICAgICAgICAgICAgKyAndGhlIFdpdGNoZXIgMyBTY3JpcHQgbWVyZ2VyLiBGb3IgbW9yZSBpbmZvcm1hdGlvbiBzZWU6ICcsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfVxyXG4gICAgICAgICAgICA8YSBvbkNsaWNrPXsoKSA9PiB1dGlsLm9wbignaHR0cHM6Ly93aWtpLm5leHVzbW9kcy5jb20vaW5kZXgucGhwL01vZGRpbmdfVGhlX1dpdGNoZXJfM193aXRoX1ZvcnRleCcpfT5cclxuICAgICAgICAgICAgICB7dCgnTW9kZGluZyBUaGUgV2l0Y2hlciAzIHdpdGggVm9ydGV4LicsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfVxyXG4gICAgICAgICAgICA8L2E+XHJcbiAgICAgICAgICA8L3A+XHJcbiAgICAgICAgPC9kaXY+XHJcbiAgICAgICAgPGRpdiBzdHlsZT17eyBoZWlnaHQ6ICc4MCUnIH19PlxyXG4gICAgICAgICAgPHA+e3QoJ1BsZWFzZSBub3RlOicsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfTwvcD5cclxuICAgICAgICAgIDx1bD5cclxuICAgICAgICAgICAgPGxpPnt0KCdGb3IgV2l0Y2hlciAzLCB0aGUgbW9kIHdpdGggdGhlIGxvd2VzdCBpbmRleCBudW1iZXIgKGJ5IGRlZmF1bHQsIHRoZSBtb2Qgc29ydGVkIGF0IHRoZSB0b3ApIG92ZXJyaWRlcyBtb2RzIHdpdGggYSBoaWdoZXIgaW5kZXggbnVtYmVyLicsIHsgbnM6IEkxOE5fTkFNRVNQQUNFIH0pfTwvbGk+XHJcbiAgICAgICAgICAgIDxsaT57dCgnWW91IGFyZSBhYmxlIHRvIG1vZGlmeSB0aGUgcHJpb3JpdHkgbWFudWFsbHkgYnkgcmlnaHQgY2xpY2tpbmcgYW55IExPIGVudHJ5IGFuZCBzZXQgdGhlIG1vZFxcJ3MgcHJpb3JpdHknLCB7IG5zOiBJMThOX05BTUVTUEFDRSB9KX08L2xpPlxyXG4gICAgICAgICAgICA8bGk+e3QoJ0lmIHlvdSBjYW5ub3Qgc2VlIHlvdXIgbW9kIGluIHRoaXMgbG9hZCBvcmRlciwgeW91IG1heSBuZWVkIHRvIGFkZCBpdCBtYW51YWxseSAoc2VlIG91ciB3aWtpIGZvciBkZXRhaWxzKS4nLCB7IG5zOiBJMThOX05BTUVTUEFDRSB9KX08L2xpPlxyXG4gICAgICAgICAgICA8bGk+e3QoJ1doZW4gbWFuYWdpbmcgbWVudSBtb2RzLCBtb2Qgc2V0dGluZ3MgY2hhbmdlZCBpbnNpZGUgdGhlIGdhbWUgd2lsbCBiZSBkZXRlY3RlZCBieSBWb3J0ZXggYXMgZXh0ZXJuYWwgY2hhbmdlcyAtIHRoYXQgaXMgZXhwZWN0ZWQsICdcclxuICAgICAgICAgICAgICArICdjaG9vc2UgdG8gdXNlIHRoZSBuZXdlciBmaWxlIGFuZCB5b3VyIHNldHRpbmdzIHdpbGwgYmUgbWFkZSBwZXJzaXN0ZW50LicsXHJcbiAgICAgICAgICAgICAgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9PC9saT5cclxuICAgICAgICAgICAgPGxpPnt0KCdZb3UgY2FuIGNoYW5nZSB0aGUgd2F5IHRoZSBwcmlvcml0aWVzIGFyZSBhc3NnaW5lZCB1c2luZyB0aGUgXCJTd2l0Y2ggVG8gUG9zaXRpb24vUHJlZml4IGJhc2VkXCIgYnV0dG9uLiAnXHJcbiAgICAgICAgICAgICAgKyAnUHJlZml4IGJhc2VkIGlzIGxlc3MgcmVzdHJpY3RpdmUgYW5kIGFsbG93cyB5b3UgdG8gc2V0IGFueSBwcmlvcml0eSB2YWx1ZSB5b3Ugd2FudCBcIjUwMDAsIDY5OTk5LCBldGNcIiB3aGlsZSBwb3NpdGlvbiBiYXNlZCB3aWxsICdcclxuICAgICAgICAgICAgICArICdyZXN0cmljdCB0aGUgcHJpb3JpdGllcyB0byB0aGUgbnVtYmVyIG9mIGxvYWQgb3JkZXIgZW50cmllcyB0aGF0IGFyZSBhdmFpbGFibGUuJyxcclxuICAgICAgICAgICAgICB7IG5zOiBJMThOX05BTUVTUEFDRSB9KX08L2xpPlxyXG4gICAgICAgICAgICA8bGk+e3QoJ01lcmdlcyBnZW5lcmF0ZWQgYnkgdGhlIFdpdGNoZXIgMyBTY3JpcHQgbWVyZ2VyIG11c3QgYmUgbG9hZGVkIGZpcnN0IGFuZCBhcmUgbG9ja2VkIGluIHRoZSBmaXJzdCBsb2FkIG9yZGVyIHNsb3QuJywgeyBuczogSTE4Tl9OQU1FU1BBQ0UgfSl9PC9saT5cclxuICAgICAgICAgIDwvdWw+XHJcbiAgICAgICAgICA8QlMuQnV0dG9uXHJcbiAgICAgICAgICAgIG9uQ2xpY2s9eygpID0+IHRvZ2dsZU1vZHNTdGF0ZShmYWxzZSl9XHJcbiAgICAgICAgICAgIHN0eWxlPXt7IG1hcmdpbkJvdHRvbTogJzVweCcsIHdpZHRoOiAnbWluLWNvbnRlbnQnIH19XHJcbiAgICAgICAgICA+XHJcbiAgICAgICAgICAgIHt0KCdEaXNhYmxlIEFsbCcpfVxyXG4gICAgICAgICAgPC9CUy5CdXR0b24+XHJcbiAgICAgICAgICA8YnIgLz5cclxuICAgICAgICAgIDxCUy5CdXR0b25cclxuICAgICAgICAgICAgb25DbGljaz17KCkgPT4gdG9nZ2xlTW9kc1N0YXRlKHRydWUpfVxyXG4gICAgICAgICAgICBzdHlsZT17eyBtYXJnaW5Cb3R0b206ICc1cHgnLCB3aWR0aDogJ21pbi1jb250ZW50JyB9fVxyXG4gICAgICAgICAgPlxyXG4gICAgICAgICAgICB7dCgnRW5hYmxlIEFsbCAnKX1cclxuICAgICAgICAgIDwvQlMuQnV0dG9uPlxyXG4gICAgICAgIDwvZGl2PlxyXG4gICAgICA8L0ZsZXhMYXlvdXQuRmxleD5cclxuICAgIDwvQlMuUGFuZWw+XHJcbiAgKTtcclxufVxyXG4iXX0=