/* eslint-disable */
import * as React from 'react';
import * as BS from 'react-bootstrap';
import { I18N_NAMESPACE } from '../common';

import { FlexLayout, util } from 'vortex-api';
import { useTranslation } from 'react-i18next';

interface InfoComponentProps {
  onToggleModsState: (enable: boolean) => void;
}

export default function InfoComponent(props: InfoComponentProps) {
  const { onToggleModsState } = props;
  const t = useTranslation(I18N_NAMESPACE).t;
  const toggleModsState = React.useCallback((enable) => {
    onToggleModsState(enable);
  }, [onToggleModsState]);

  return (
    <BS.Panel id='loadorderinfo'>
      <h2>{t('Managing your load order', { ns: I18N_NAMESPACE })}</h2>
      <FlexLayout.Flex style={{ height: '30%' }}>
        <div>
          <p>
            {t('You can adjust the load order for The Witcher 3 by dragging and dropping '
              + 'mods up or down on this page.  If you are using several mods that add scripts you may need to use '
              + 'the Witcher 3 Script merger. For more information see: ', { ns: I18N_NAMESPACE })}
            <a onClick={() => util.opn('https://wiki.nexusmods.com/index.php/Modding_The_Witcher_3_with_Vortex')}>
              {t('Modding The Witcher 3 with Vortex.', { ns: I18N_NAMESPACE })}
            </a>
          </p>
        </div>
        <div style={{ height: '80%' }}>
          <p>{t('Please note:', { ns: I18N_NAMESPACE })}</p>
          <ul>
            <li>{t('For Witcher 3, the mod with the lowest index number (by default, the mod sorted at the top) overrides mods with a higher index number.', { ns: I18N_NAMESPACE })}</li>
            <li>{t('You are able to modify the priority manually by right clicking any LO entry and set the mod\'s priority', { ns: I18N_NAMESPACE })}</li>
            <li>{t('If you cannot see your mod in this load order, you may need to add it manually (see our wiki for details).', { ns: I18N_NAMESPACE })}</li>
            <li>{t('When managing menu mods, mod settings changed inside the game will be detected by Vortex as external changes - that is expected, '
              + 'choose to use the newer file and your settings will be made persistent.',
              { ns: I18N_NAMESPACE })}</li>
            <li>{t('You can change the way the priorities are assgined using the "Switch To Position/Prefix based" button. '
              + 'Prefix based is less restrictive and allows you to set any priority value you want "5000, 69999, etc" while position based will '
              + 'restrict the priorities to the number of load order entries that are available.',
              { ns: I18N_NAMESPACE })}</li>
            <li>{t('Merges generated by the Witcher 3 Script merger must be loaded first and are locked in the first load order slot.', { ns: I18N_NAMESPACE })}</li>
          </ul>
          <BS.Button
            onClick={() => toggleModsState(false)}
            style={{ marginBottom: '5px', width: 'min-content' }}
          >
            {t('Disable All')}
          </BS.Button>
          <br />
          <BS.Button
            onClick={() => toggleModsState(true)}
            style={{ marginBottom: '5px', width: 'min-content' }}
          >
            {t('Enable All ')}
          </BS.Button>
        </div>
      </FlexLayout.Flex>
    </BS.Panel>
  );
}
